name: lint
on: [ pull_request ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup-env
        with:
          python-version: "3.10"
      - name: run pylint
        run: |
          pylint confz
