name: test
on: [ pull_request ]
jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-env
        with:
          python-version: ${{ matrix.python-version }}
      - name: run pytest
        run: |
          pytest -W error
