name: typecheck
on: [ pull_request ]
jobs:
  run-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-env
        with:
          python-version: "3.13"
      - name: run mypy
        run: |
          mypy confz
